### ISSUE TITLE
Bugs in lz4cli\lz4io.pas

### ISSUE THREAD

**Issue by Acetylator** [atelierw/LZ4Delphi#1]
Hi Jose, first of all thank you for your work! I have been examining your code and have found a coouple of possible bugs in lz4io.pas. For example, in LZ4IO_compressFilename you use multiple conditional Exit() calls in your code - if they are actually executed you will get memory leaks since you don't free free memory and objects on exit. You just have this:
    freemem(in_buff);
    freemem(out_buff);
    fileIn.Free;;
    fileOut.Free;
at the end of the procedure. I think you should use try..finally clause to eliminate possible leaks.  I have checked only LZ4IO_compressFilename procedure, but as I see, you use such an approach also in other parts of your code.

Regards, Ace.

**Comment by atelierw** [comment]
Thank you for taking the time to find those bugs.
I believe I have fixed them all now.
Regards, Jose
