### ISSUE TITLE
Error compiling lz4common.pas under XE7

### ISSUE THREAD

**Issue by Acetylator** [atelierw/LZ4Delphi#2]
Hi Jose,
Delphi XE7 refuses to compile lz4common.pas. The problem is here:
        pCardinal(d)[0] := pCardinal(s)[0];
        pCardinal(d)[1] := pCardinal(s)[1];
Unfortunately right now I am not on PC with Delphi, but the error was near first [0] in the first line - unfortunately I don't remember exact error message - it was something like "Array type required". Tomorrow I will be able to give you exact error message that Delphi compiler gives.
Regards, Ace.

**Comment by atelierw** [comment]
I have no Delphi above XE2, so I am curious what's the error.
Regards,
Jose

**Comment by Acetylator** [comment]
Found it. You need to add {$POINTERMATH ON} to lz4common.pas. Though you define this in lz4.pas, but if you have a project which uses only lz4common.pas (and not lz4.pas), pointer math must be turned on separately. Maybe it would be a good idea to add this directive to all your units in \lib\delphi which require pointer math to be turned on.

**Comment by atelierw** [comment]
Ah OK:)
Thanks a lot!
