### ISSUE TITLE
More possible memory leaks

### ISSUE THREAD

**Issue by Acetylator** [atelierw/LZ4Delphi#3]
More possible memory leaks found:
procedure LZ4F_compressFrame in lz4frame.pas (freemem() at the end of the procedure should be in try..finally block).
Also, in LZ4F_compressBegin in lz4frame.pas you use this:
    if cctxPtr.lz4CtxLevel < targetCtxLevel then
    begin
        freemem(cctxPtr.lz4CtxPtr);
        if (cctxPtr.prefs.compressionLevel < minHClevel) then
            cctxPtr.lz4CtxPtr := LZ4_createStream()
        else
            cctxPtr.lz4CtxPtr := LZ4_createStreamHC();
        cctxPtr.lz4CtxLevel := targetCtxLevel;
    end;
You do not check whether stream was actually created. In case of memory allocation error cctxPtr.lz4CtxPtr will be Nil - there should be a check for it.

**Comment by atelierw** [comment]
Oh, yeah, but note that 99.995% of what I did was a mere translation of the original, namely @ release lz4-r127.
In the original we had:
    if (cctxPtr->lz4CtxLevel < targetCtxLevel)
        {
             FREEMEM(cctxPtr->lz4CtxPtr);
                if (cctxPtr->prefs.compressionLevel<minHClevel)
                    cctxPtr->lz4CtxPtr = (void_)LZ4_createStream();
                else
                    cctxPtr->lz4CtxPtr = (void_)LZ4_createStreamHC();
                cctxPtr->lz4CtxLevel = targetCtxLevel;
         }

Thank you!

Regards,

Jose

**Comment by Acetylator** [comment]
Yes, I understand that. Are you going to correct this behavior or you leave it like it is? If left, probably nothing happens, but it seems to me as (at least theoretical) source of trouble.

**Comment by atelierw** [comment]
It is indeed a potential source of trouble, but I will keep as it is to remain close to the original.
This is my logic, may be a bit illogical.
Note that I fixed the first issues you found because my approach was a departure from the original, the original is a command line application that closes when finished so the leaks are not really important there. In my departure leaks matter.
