### ISSUE TITLE
Way to avoid dependency on MSVCRT.DLL?

### ISSUE THREAD

**Issue by Acetylator** [atelierw/LZ4Delphi#4]
Not actually an issue, rather a question. In LZ4Externals.pas there is a number of external function from msvcrt.dll defined (_calloc, _free, _malloc, _memmove, _memcpy, _memset, __allmul, calloc, free, malloc, memcpy, memmove, memset).
So, basically, the whole thing will work _ONLY_ if MSVCRT.DLL is present on the target machine?
Unfortunately, I have zero experience with VC, so I have to rely on others knowledge. As stated in https://msdn.microsoft.com/en-us/library/bb985746.aspx, " in most cases you can rely on MSVCRT.DLL being available on your target machines." This part: "in most cases" troubles me.
I also know, that MSCVRT.DLL is shipped with Windows since Windows 2000. And for my software, target OS is Windows XP and later - so I see a possible problem here.
I want to make my code 200% bulletproof and it MUST work on every machine with Windows XP and later and even slightest possibility that my code will throw message to the user that DLL was not found is unacceptable.
What can I do to achieve this? Should I use your Delphi port (libraries from \lib\delphi\ instead of precompiled VS .obj files? Is there any way to avoid this DLL dependency?

Thank you in advance, Ace.

**Comment by atelierw** [comment]
I believe MSVCRT.DLL will be more omnipresent than any other library because device drivers rely on it.
I just checked it is present in Windows 10 Preview.
__allmul is not from MSVCRT.DLL

For speed, I would recommend using the precompiled VS .obj, , they are clearly faster.

Regards,

Jose
